defmodule Advent2018.Day2ATest do
  use ExUnit.Case, async: true

  test "simple" do
    input = """
    abbcde
    abcccd
    """

    assert Day2A.checksum(input) == 1
  end

  test "example 1" do
    input = """
    abcdef
    bababc
    abbcde
    abcccd
    abcdee
    ababab
    """

    assert Day2A.checksum(input) == 9
  end

  test "example 2" do
    input = """
    abcdef
    bababc
    abbcde
    abcccd
    aabcdd
    abcdee
    ababab
    """

    assert Day2A.checksum(input) == 12
  end

  test "full text" do
    input = """
    omlvgpokxfnctqyersabjwzizp
    omlvtdhxxflctqyersabjwziup
    omlvgdakxfnctqyersabzmziup
    omlvgdhkxfnchqyersarjwsiup
    omlvgdnkxfnctqyersabhwziuq
    omvlgdhkxfnctqyersajjwziup
    fmlvgdbkxfnctqyersabjwzqup
    omlvcdhexfnctqyersibjwziup
    omlvgdhkxfnctqyersoyjnziup
    omdbgdhpxfnctqyersabjwziup
    omlvgdbkxfnctiyersabjwziwp
    omlogdhkxfncpqyersabjfziup
    omlvgdhkxfncxayersabwwziup
    omlvgdhkxfgctqyepsabjnziup
    omlvzdhkxfnctqyerxabjwoiup
    orlvtdhoxfnctqyersabjwziup
    omgvgdhkxfnctqyetsarjwziup
    omlvgdhkxunctcqersabjwziup
    omlvgdhkxfnctqyertakjwziun
    omlvhdhkxfhetqyersabjwziup
    omlvjdhkxfnctqyersabjtzirp
    omsvgdhkifnctqyeryabjwziup
    ohlvgdhkxfncteyersabtwziup
    omlvgdhkxjqctqyerkabjwziup
    omljgdhkxfncxqiersabjwziup
    omlvgdhkxvnctqyetscbjwziup
    omlvgdhxxfnctqykrsabjwziui
    omlbgdhkxfnetqyersabjwliup
    omlvgvhkxfnctqyerjabjwzwup
    wmlvgdhkxfnctqyyrsabjwziuc
    omlvgdhkufnctqxersabjwpiup
    omlvgdtkxfnctqyercvbjwziup
    omtvgdhkxfnctqygrsmbjwziup
    omlvgdbkxfnctqyersagjwzrup
    omlvgdpksfnctqyorsabjwziup
    omlvgdlkxfnctqyerhaajwziup
    omlvgdhkxfnctqyersabjwkiqh
    omlvgdykxfnctqdersdbjwziup
    omligdhklfnctpyersabjwziup
    omlvzdhkxfnctryersabjwziap
    nmlvgdqkxfnctqyemsabjwziup
    omlvgdhkxoncqqyersabjyziup
    otlvgdhkxfnctqyersabjwzzhp
    omlvgdhvxfnctqyirsabjwziue
    omlvgohkxfnctqjersabjwzeup
    omlngdhkxfnytqyersabjwsiup
    gmlvgbhkxfnctqyersabjwziyp
    nmlvgxhkxfnctqyxrsabjwziup
    omlvwdhkufnctqyerfabjwziup
    omlvqdhkxfnctqyersabfmziup
    omlvgdhkxfnctqlerscbjeziup
    omlvgdhkxfncxqyerjabjgziup
    omlvgdhkxwnctqyersvbjwriup
    ozlvgdhkxfnctqyersabjjziuj
    omlvguhkxfnctqyersabjwznut
    ozlvwdhkxfactqyersabjwziup
    oplvgdhkxfnctqyersakjwiiup
    omlkgbhkxfnctqyetsabjwziup
    oukvgdhkxfnctqyerslbjwziup
    omllgwhkxfnctqyersasjwziup
    omlvgdqkvfnctqyjrsabjwziup
    omlvguhkxfnctqyepsakjwziup
    oblvgdhkxfnctqyersibjwciup
    omlvgdhkxfpetqyersnbjwziup
    omlvgdhkxfnctqyersabgwpmup
    ohlvgdhkxfnctqyersgbjwdiup
    omlvgkhkxfnctqyarsabjwziuj
    omtvgdhkxfnctqoersabjwzfup
    omlvgdhkxfncbqyersafjwzkup
    amlvgdhkmfnctqyorsabjwziup
    omlvndhkxfnctbyersagjwziup
    oslvgdhkxfactqyersabjwziip
    omlvgdhkxfnrtqyerumbjwziup
    omjvgdhaxfnctqyersajjwziup
    omlvgdhkxfyctqyersabjvziuf
    omlvgdhkxfgctqyervabjwzuup
    oclvhdhkxfnctqyirsabjwziup
    omlvgdhkxfnctqyrrsbbjwsiup
    nmlvghhkxfnctqyersayjwziup
    omlvgdhksfnzcqyersabjwziup
    omlvgdhbxknctqyerzabjwziup
    omlvgdhsxflctqyercabjwziup
    omlvgdhkxfncthyersabjpzgup
    omlvgdhkxfnhtqyersadjwzilp
    omlvgdhyxfnctqyershjjwziup
    omlvhdhkxfnctqytesabjwziup
    omlvgbhkxfnctqyhrsabjwmiup
    omlvnyhkxfnctqyersabbwziup
    omlvgdhkxfnhzqcersabjwziup
    omljgdhkvynctqyersabjwziup
    omrvgdhkxfnctqysrsabjmziup
    omlvgdhgxenctqyerfabjwziup
    omlvgdokxfncvqyersasjwziup
    omlvguhkxfnctqyersabbbziup
    imkvgdhkxfnctqyqrsabjwziup
    omlvgdikxfnctwyersabbwziup
    oulvgdhuxfngtqyersabjwziup
    omlvgdhkxfdctqqbrsabjwziup
    omlvgdhbofnctqyersmbjwziup
    omlzgdhkxfnctzyecsabjwziup
    oflvgdhkxfnctqyerpabjwzcup
    ommvgdhkxfnctqyicsabjwziup
    omlvgdhkxfnctqyewsabjwzisd
    ojlvgdhfxfnctqyersabjwzihp
    smlvgdhkxfnctqyzrsabjwaiup
    ohlvgdhkxfnctqyersabnwziue
    jslvgdhkxfnctqdersabjwziup
    omlvgdhkdenctwyersabjwziup
    orljgdhkxbnctqyersabjwziup
    omlvgdhkxfnctaaersabjwzrup
    qmlvgdhknfncqqyersabjwziup
    omlvgdhkxfnctqyerssbjwncup
    omlvgdhkxynctqdercabjwziup
    omivgdhpxfnctqiersabjwziup
    omuvgdbkxfnctqyersajjwziup
    omlvbdokxfnctqyehsabjwziup
    gmlvgdhkxcnctqyemsabjwziup
    hmlvgdhkxfncsqyersabjwzidp
    omlvgdhkxftztqytrsabjwziup
    omlvgdhkxfnatqyeesabjbziup
    omlvodhkxfnctqbirsabjwziup
    omlvgdhsifnctqyersabjwziop
    oyvvgdhkxfnctqyersabjwzinp
    qmlvgdhkxfnctqyersdbawziup
    omlvguhkxfncuqyersabjwzipp
    omspgdhkxfnctqyersabjwzifp
    omlvgdhkxfnamqyeryabjwziup
    omlvgdhkngnctqyxrsabjwziup
    omdvcdhkxfnctqynrsabjwziup
    omyvgdhkxfnctqyeryabjyziup
    hmlvgdhkxfnctqyersabjwzwap
    ombvgdhkxfyctqyersabjwziuk
    omlvadhkxfnctqyersoqjwziup
    ollugdhkxfnctqyersabjwzizp
    omlvgdhkxfncvqmersabjwiiup
    omlvgdkkxfnupqyersabjwziup
    omlvgdhkxfncratersabjwziup
    oklvgdskxfnctqyersabjkziup
    omlvgdhkxfnctqyernebgwziup
    omsvgdhkxfnctqyersaejwziuv
    omlvgdhkxfrctlynrsabjwziup
    omlggdhkxfnctqyersbbjmziup
    omlvgdhfxfnctqyehrabjwziup
    omqvgdhkxfnctqcersabjwzfup
    omlvgdhklfncqxyersabjwziup
    omlvgxhkxfnctqyersabebziup
    omlfgdhkxfnctjyersabkwziup
    omlvgdhkxfnctqysrtabjwqiup
    omlvgdhkxfnltqaersabfwziup
    ofhvgdhkxfnctqyessabjwziup
    omlvpdekxfnctqyerscbjwziup
    omlvcdhkxlnbtqyersabjwziup
    omlvfdhkxfnctqyersabjwrnup
    omlvddhkxfncdqyersabjwziut
    omlvgdhkxfnctqxersabjhiiup
    omidgdhkxfnctqyeysabjwziup
    omlogdhkxfnptqyersabjwniup
    omlvgdhkxfnwthyersabjwziuz
    omevgdhkxgnctbyersabjwziup
    omlvgdhkxfnytqyersabjozuup
    omlvgvhkxfmctqyersabjwziuw
    oelvgdhkxfoctqyersadjwziup
    lmlvgdhkxfnctqeersabjwzisp
    omlvgdhkxfcctqyersasjwzibp
    gmlvgdhkyfnctqyersabjwziuz
    omlvgdhkxfnctslersabjwziuf
    omlvgehkxfnctqyeosabjwziyp
    otlggdhkxfjctqyersabjwziup
    bmjvgdhixfnctqyersabjwziup
    omlvgqhkxfnctqdezsabjwziup
    omlvgbhkxfnciqnersabjwziup
    omlvgdhlxfnctqydrsdbjwziup
    omlvgdhkxfncfqyersabjwxinp
    ymlvgdhkxfnctqyersabhwziui
    omdvgdhkxfnctqyersabjwxdup
    bmlvgdhkxfnwtwyersabjwziup
    dmlvgmhkxfnctqyxrsabjwziup
    omlvgdhkxbnntqyersabjiziup
    omlvgdhkmfnctlyersgbjwziup
    omlvgdhkxfnctqhersablwzixp
    ommvgdhkxfwctqyersabnwziup
    omlkgdhjxfnctqyersabjwjiup
    omlvgdhrxfnctqyeasabjnziup
    omvvgdhkxtnctqyersabjtziup
    omlvgdhkufgctqyersabfwziup
    omqvgwhkxfnctqyevsabjwziup
    oalvgdhkyfyctqyersabjwziup
    omlvgdhkxfnctqyefvabjwhiup
    jmlvgdakxfnctqyersabjwtiup
    gmlvgmhkxfnctqyersaqjwziup
    omlvgdhkxcnctqydrszbjwziup
    omlvgdhkxfnctxnersxbjwziup
    omlvgyhkxfnctqyersabjeaiup
    omlcgdhkxfncvqyersabjoziup
    omlvgdhkxfycttyercabjwziup
    omlmgdhkpsnctqyersabjwziup
    lmlvglhkxfnctqdersabjwziup
    omlvgdhxdfncoqyersabjwziup
    omlvgdhkxfnctqyersabjwkixv
    oplvgdhkxfnctiyersabjoziup
    omlvgdnkxfnctdyersebjwziup
    omlvguckxfnctqwersabjwziup
    omlvgdhojfnctqyersabjoziup
    opjvxdhkxfnctqyersabjwziup
    omevgdhkdflctqyersabjwziup
    omlvgilkxfncaqyersabjwziup
    omlvgdhkqfnctqyersabunziup
    dmlvgdhkxrnctqyerssbjwziup
    omlvgdzcxfnctqyersabjwniup
    omlvgdhkxfnctqyeraabpsziup
    omlvgdhkxfnctqlersabjtziul
    omlvgbhkxfnctqyeysabjwpiup
    omlvgdhvxfnmttyersabjwziup
    omlvgdhkxznctqyersabewziua
    oqlvgdhkxfnctqjersabjfziup
    omlvgdhkqfnctqyoysabjwziup
    omlvgdhkxfnctqylrzabbwziup
    oalvguhkxfnctqyersabawziup
    omlvgdokxfncvqyersasjlziup
    omlvgdhkcfnctqyersazjwzfup
    oslvgdhpxfnctqyhrsabjwziup
    omlvgdhkxfnotqcqrsabjwziup
    umlvgdhlxfnctqyersnbjwziup
    oxlvgdhkxfnktjyersabjwziup
    omlvgdhkxhncnqyersabjwzirp
    jmlvgdhkxfncfqyersabjwzqup
    omlvgdhkbfnutvyersabjwziup
    omhvgddkxfnctqyersabqwziup
    omlvgdukxfnbtqyersabjwzjup
    oylvndhkxfnctqversabjwziup
    omlvgdhkcfnctqyersamjwfiup
    omlvgdskxfnctqyerssbjgziup
    qmlvgdhkxfncxqyersabiwziup
    omlvghhkxfnctwyersaljwziup
    omlvgdhkpfnbtqyersnbjwziup
    omlvgthkxfnctnyersabjwziut
    omlvgdhkpfnctqyeisabjfziup
    omlvgdhrxrnctqyersabjwzigp
    omlvjdhkxfnctqyersabpwwiup
    omlvgdhkxfnctsyersabjwzixl
    amlvgdhktfnctqyersabfwziup
    oklvvdhkxfnctoyersabjwziup
    rmlvgdhkxfncwqyersabxwziup
    omlvgdhkxfnctqyersabiwzjfp
    omlvgehkxfnctqyersebjzziup
    omlvgdhkxfncaqyersabwwzoup
    omlvgdhkxfncjqyersanjwfiup
    omlvgdhkwfnctqyersqbjwziux
    omrvgdhjxfnctqyeksabjwziup
    omlvgdhkxfnctpyersaftwziup
    """

    assert Day2A.checksum(input) == 7105
  end
end
